### ISSUE TITLE
멘토님 코드리뷰 기반 리팩토링

### ISSUE THREAD

**Issue by chaee813** [Step3-kakao-tech-campus/Team5_BE#120]
## 📌 설명
> 6주차 코드리뷰 기반 리팩토링

## ✅ 할 일
- [x] is_active → isActive로 변경
- [x] PortfolioService에서의 메서드들이 길다 → 더 작은 메서드로 분리
- [x] ResultActions의 실행과 응답바디의 로깅부분이 반복 → 메서드로 추출

## 📃 참고 자료
-

**Comment by seokwns** [comment]
DTO 변환 시에 이미지 사이즈 처리 문제는 
ImageEncoder에서 포트폴리오에 해당하는 ImageItem을 찾지 못할 경우 빈 문자열을 추가하도록 구현했기 때문에
이 부분은 수정하지 않아도 될 것 같습니다!

**Comment by chaee813** [comment]
아하 그렇군요! 이미지쪽 코드는 거의 못 봐서ㅠㅠ 감사합니다!!
